apiVersion: v1
kind: Service
metadata:
  name: logger-service

spec:
  selector:
    app: logger-service
  ports:
    - name: logger-service-port
      protocol: TCP
      port: 8083
      targetPort: 80
