services:
  frontend-service:
    build: ./frontend-service
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1

  broker-service:
    build: ./broker-service
    restart: always
    ports:
      - 8081:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: amqp://guest:guest@rabbitmq-amqp:5672
      LOGGER_PORT_RPC: 5000
      LOGGER_PORT_GRPC: 6000

  authentication-service:
    build: ./authentication-service
    restart: always
    ports:
      - 8082:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: postgresql://postgres:password@postgres-db:5432/users?sslmode=disable&timezone=UTC&connect_timeout=5

  logger-service:
    build: ./logger-service
    restart: always
    ports:
      - 8083:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      URI: mongodb://mongo-db:27017
      Username: mongo
      Password: password

  mail-service:
    build: ./mail-service
    restart: always
    ports:
      - 8084:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      Host: mailhog-smtp
      Port: 1025
      Username: mailhog
      Password: password
      Encryption: none

  listener-service:
    build: ./listener-service
    restart: always
    ports:
      - 8085:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: amqp://guest:guest@rabbitmq-amqp:5672

  postgres-db:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./authentication-service/dal/data:/var/lib/postgresql/data

  mongo-db:
    image: mongo:4.2.16-bionic
    restart: always
    ports:
      - 27017:27017
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DB: logs
    volumes:
      - ./logger-service/dal/data:/data/db

  mailhog-smtp:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    deploy:
      mode: replicated
      replicas: 1

  rabbitmq-amqp:
    image: rabbitmq:3.12-alpine
    restart: always
    ports:
      - 5672:5672
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./listener-service/dal/data:/var/lib/rabbitmq
