services:
  frontend-service:
    build: ./frontend-service
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1

  broker-service:
    build: ./broker-service
    restart: always
    ports:
      - 8081:80
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build: ./authentication-service
    restart: always
    ports:
      - 8082:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: postgresql://postgres:password@localhost:5432/users?sslmode=disable&timezone=UTC&connect_timeout=5

  postgres-db:
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./authentication-service/db/data:/var/lib/postgresql/data
