apiVersion: v1
kind: Service
metadata:
  name: authentication-service

spec:
  selector:
    app: authentication-service
  ports:
    - name: authentication-service-port
      protocol: TCP
      port: 8082
      targetPort: 80
