apiVersion: v1
kind: Service
metadata:
  name: listener-service

spec:
  selector:
    app: listener-service
  ports:
    - name: listener-service-port
      protocol: TCP
      port: 8085
      targetPort: 80
