apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service

spec:
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      containers:
        - name: broker-service
          image: dmitrywhite/broker-service:1.0.0
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
          env:
            - name: DSN
              value: amqp://guest:guest@rabbitmq-amqp:5672
            - name: LOGGER_PORT_RPC
              value: "5000"
            - name: LOGGER_PORT_GRPC
              value: "6000"
