apiVersion: v1
kind: Service
metadata:
  name: broker-service

spec:
  selector:
    app: broker-service
  ports:
    - name: broker-service-port
      protocol: TCP
      port: 8081
      targetPort: 80
