apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: dmitrywhite/frontend-service:1.0.0
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: http://broker-service.info
