apiVersion: v1
kind: Service
metadata:
  name: frontend-service

spec:
  selector:
    app: frontend-service
  ports:
    - name: frontend-service-port
      protocol: TCP
      port: 8080
      targetPort: 80
