apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-smtp

spec:
  selector:
    matchLabels:
      app: mailhog-smtp
  template:
    metadata:
      labels:
        app: mailhog-smtp
    spec:
      containers:
        - name: mailhog-smtp
          image: mailhog/mailhog:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 1025
            - containerPort: 8025
