apiVersion: v1
kind: Service
metadata:
  name: mailhog-smtp

spec:
  selector:
    app: mailhog-smtp
  ports:
    - name: mailhog-smtp-port
      protocol: TCP
      port: 1025
      targetPort: 1025
    - name: mailhog-smtp-web-port
      protocol: TCP
      port: 8025
      targetPort: 8025
