apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-amqp

spec:
  selector:
    app: rabbitmq-amqp
  ports:
    - name: rabbitmq-amqp-port
      protocol: TCP
      port: 5672
      targetPort: 5672
